add debug echo inside functions

diff --git a/test_init b/test_init
--- a/test_init
+++ b/test_init
@@ -1,20 +1,27 @@
 #!/usr/bin/env bash
 FAILURES=0
 
+apply_error() {
+    # expecting an error and a change, so code 6
+    echo "apply_error" $@
+    sudo puppet apply --detailed-exitcodes --debug "$@" || [ $? -eq 6 ] || echo 'Error' $((++FAILURES))
+}
 apply() {
+    echo "apply" $@
     sudo puppet apply --detailed-exitcodes --debug "$@" || [ $? -eq 2 ] || echo 'Error' $((++FAILURES))
 }
 check() {
+    echo "check" $@
     "$@" || echo 'Error' $((++FAILURES))
 }
 uncheck() {
+    echo "uncheck" $@
     ! "$@" || echo 'Error' $((++FAILURES))
 }
 
 # uncheck which brew
 #  - CI nodes have brew installed)
 #  - Removing brew before tests is not an option: ruby is provided through brew
-echo 'Apply init.pp...'
 apply tests/init.pp
 check which brew
 
